version: '3.5'

services:

  grocy:
    deploy:
      mode: global
      restart_policy:
        condition: any
    image: linuxserver/grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - grocy:/config
    ports:
      - 9283:80
      


  portainer:
    environment:
      - acme_flags=${acme_flags:-""}
      - stackname=${stack_name:-technocore}
      - stack_name=${stack_name:-technocore}
      - image_provider=${image_provider:-scififarms}
      # Tempaltes are cool: https://docs.docker.com/engine/swarm/services/#create-services-using-templates
      - DOCKER_HOSTNAME={{ .Node.Hostname }}
      - TAG=${TAG:-latest}
      # 1 day = 86400 seconds
      - image_refresh_time=${image_refresh_time:-86400}
      - host_working_dir=$PWD
    depends_on:
      - mqtt
    deploy:
      mode: global
      restart_policy:
        condition: any
    image: ${image_provider:-scififarms}/technocore-portainer:${TAG:-latest}
    <<: *logging-defaults
    networks:
      - web
    ports:
      - "9000:9000"
    secrets:
      - source: portainer_acme_env
        target: acme_env
      - source: portainer_cert_bundle
        target: cert
      - source: portainer_key
        target: key
      - source: ca_bundle
        target: ca
      - source: portainer_mqtt_username
        target: mqtt_username
      - source: portainer_mqtt_password
        target: mqtt_password
      - source: portainer_token
        target: token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./:/var/run/technocore
      - portainer:/data
      - portainer-acme:/acme.sh/
      - ${portainer_live_mount:-./empty/:/opt/.dummy}
      - ${portainer_migrations_live_mount:-./empty/:/opt/.migrations_dummy}
  
  mariadb:
    deploy:
      mode: global
      restart_policy:
        condition: any
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=suitecrm
      - MARIADB_DATABASE=suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - web
    volumes:
      - 'mariadb:/bitnami'
  
  suitecrm:
    deploy:
      mode: global
      restart_policy:
        condition: any
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=suitecrm
      - SUITECRM_DATABASE_NAME=suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8080:80'
      - '44380:443'
    networks:
      - web
    volumes:
      - 'suitecrm:/bitnami'
      

secrets:
  portainer_acme_env:
    name: ${stack_name:-technocore}_portainer_acme_env
    external: true
  portainer_cert_bundle:
    name: ${stack_name:-technocore}_portainer_cert_bundle
    external: true
  portainer_key:
    name: ${stack_name:-technocore}_portainer_key
    external: true
  portainer_mqtt_username:
    name: ${stack_name:-technocore}_portainer_mqtt_username
    external: true
  portainer_mqtt_password:
    name: ${stack_name:-technocore}_portainer_mqtt_password
    external: true
  portainer_token:
    name: ${stack_name:-technocore}_portainer_token
    external: true
  health_cert_bundle:
    name: ${stack_name:-technocore}_health_cert_bundle
    external: true
  health_key:
    name: ${stack_name:-technocore}_health_key
    external: true
  health_domain:
    name: ${stack_name:-technocore}_health_domain
    external: true
volumes:
  grocy:
  loki:
  mariadb:
  portainer:
  portainer-acme:
  health:
  suitecrm:
