version: '3.5'
services:
  docs:
    command: jekyll serve
    deploy:
        mode: global
        restart_policy:
          condition: on-failure
    image: ${image_provider}/docs:${TAG}
    ports:
      - "4000:4000"
      - 35729:35729
    secrets:
      - source: docs_cert_bundle
        target: wiki_cert
      - source: docs_key
        target: wiki_key
      - source: ca
        target: ca
    volumes:
      # TODO: Make this built into the image when built. 
      - "./docs:/src"
  ha:
    depends_on:
      - vault
      - mqtt
      - ha_db
    deploy:
      # I'm usinsg replicas set to 1 instead of global because I can't seem to 
      # reboot the Home Assistant service consistantly. Setting replication to 
      # 0, then 1 seems to work though. 
      #mode: global
      replicas: 1
      restart_policy:
        condition: any
    image: ${image_provider}/home-assistant:${TAG}
    networks:
      web:
        # This was nessesary in order to get Node-RED to connect with Home Assistant.
        aliases:
          - ha.local
          - ha.scifi.farm
    ports:
      - "8123:8123"
    secrets:
      - source: ha_cert_bundle
        target: ha_cert
      - source: ha_key
        target: ha_key
        mode: 0400
      - source: ca_bundle
        target: ca
      - source: home_assistant_mqtt_username
        target: mqtt_username
      - source: home_assistant_mqtt_password
        target: mqtt_password
    # TODO: Currently, Home Assistant runs as root. Need to figure out how to run Home Assistant as a user while being hosted on a server.
    #user: ${UID}
    #volumes:
      # This allows for realtime editing of Home Assistant configs and scripts. 
      #- ../home-assistant/config/:/config
  ha_db:
    depends_on:
      - vault
    deploy:
      mode: global
      restart_policy:
        max_attempts: 20
    image: ${image_provider}/home-assistant-db:${TAG}
    networks:
      - web
    secrets:
      - source: ha_db_cert_bundle
        target: ha_db_cert
        uid: "999" # This is set in Postgres' Dockerfile
        mode: 0400
      - source: ha_db_key
        target: ha_db_key
        uid: "999" # This is set in Postgres' Dockerfile
        mode: 0400
      - source: ca
        target: ca
    user: postgres 
    volumes:
      - home-assistant-db:/var/lib/postgresql/data
      - home-assistant-db-migrations:/shell-migrations/logs/
  mqtt:
    depends_on:
      - vault
      - portainer
    deploy:
      #mode: global
      replicas: 1
      #restart_policy:
      #  condition: -failure
    image: ${image_provider}/vernemq:${TAG}
    networks:
      web:
        aliases:
          - mqtt.local
          - mqtt.scifi.farm
    ports:
      - "8883:8883"
      - "1883:1883"
    secrets:
      - source: mqtt_mqtt_username
        target: mqtt_username
      - source: mqtt_mqtt_password
        target: mqtt_password
      - source: mqtt_cert_bundle
        target: mqtt_cert
      - source: mqtt_key
        target: mqtt_key
      - source: ca_bundle
        target: ca
      - source: mqtt_token
        target: token
      - source: portainer_mqtt_username
        target: portainer_mqtt_username
      - source: portainer_mqtt_password
        target: portainer_mqtt_password
    volumes:
        #- "./mqtt/config/:/etc/rabbitmq/"
        - mqtt2:/etc/vernemq/
        # Used for creating migrations.
        #- ../vernemq/shell-migrations:/usr/share/dogfish/shell-migrations
    # Hostname is needed to persist data. 
    hostname: mqtt
    #user: vernemq
  nr:
    environment:
      # Needed to be able to connect with Home Assistant
      - NODE_EXTRA_CA_CERTS=/run/secrets/ca
    depends_on:
      - ha
      - mqtt
      - vault
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    image: ${image_provider}/node-red:${TAG}
    networks:
      - web
    ports:
      - "1880:1880"
      # Used for debugging. Simply add "--inspect" to the "start" object in /usr/src/node-red/package.json
      # Should be doable via env var: https://nodejs.org/api/cli.html#cli_node_options
      - "9229:9229"
    secrets:
      - source: nr_cert_bundle
        target: nr_cert
        #uid: ${UID}
        #mode: 0600
      - source: nr_key
        target: nr_key
        #uid: ${UID}
        #mode: 0600
      - source: ca_bundle
        target: ca
        #uid: ${UID}
        #mode: 0600
      - source: node_red_mqtt_username
        target: mqtt_username
        #uid: ${UID}
        #mode: 0600
      - source: node_red_mqtt_password
        target: mqtt_password
        #uid: ${UID}
        #mode: 0600
    user: "0" #${UID}
    volumes:
      - node-red:/data
      # If you docker cp [container hash]:/usr/src/node-red nr/src/
      # You can work with live running code by uncommenting the following volume>
      #- "./node-red:/usr/src/node-red"
  platformio:
    command: ["sh","-c","docker run --rm --name pio -t --network ${stack_name}_web -e CA=\"$$(cat /run/secrets/ca)\" -e MQTT_USERNAME=\"$$(cat /run/secrets/mqtt_username)\" -e MQTT_PASSWORD=\"$$(cat /run/secrets/mqtt_password)\" -e VAULT_TOKEN=\"$$(cat /run/secrets/token)\" --device /dev/ttyUSB0 ${image_provider}/platformio:${TAG}"]
    deploy:
        mode: global
        restart_policy:
          condition: on-failure
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    image: docker
    networks:
      - web
    secrets:
      - source: ca_bundle
        target: ca
      - source: platformio_mqtt_username
        target: mqtt_username
      - source: platformio_mqtt_password
        target: mqtt_password
      - source: platformio_token
        target: token
    user: "0" # I suspect I'll be able to remove this. I'd like to do that. 
    volumes:
      #- ./platformio/entrypoint.py:/workspace/entrypoint.py
      - /var/run/docker.sock:/var/run/docker.sock
  portainer:
    environment:
      - stackname=${stack_name}
    deploy:
      #mode: global
      replicas: 1
      restart_policy:
        condition: any
    image: ${image_provider}/portainer:${TAG}
    networks:
      - web
    ports:
      - "9000:9000"
    secrets:
      - source: portainer_cert_bundle
        target: cert
      - source: portainer_key
        target: key
      - source: ca_bundle
        target: ca
      - source: portainer_mqtt_username
        target: mqtt_username
      - source: portainer_mqtt_password
        target: mqtt_password
      - source: portainer_token
        target: token
    volumes:
      - ../portainer_old/shell-migrations:/usr/share/dogfish/shell-migrations
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer:/data
  vault:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - SKIP_SETCAP=true
      - VAULT_ADDR=https://vault.local:8200
      # This has been disabled because I don't think they are needed... But not sure enough to remove yet.
      #- CONTAINER_HOSTNAME=vault
      - VAULT_CACERT=/run/secrets/ca
      # This has been disabled because I don't think they are needed... But not sure enough to remove yet.
      #- VAULT_CA=true
    image: ${image_provider}/vault:${TAG}
    networks:
      web:
        aliases:
          - vault.local
          - vault.scifi.farm
    secrets:
      - source: vault_key
        target: /run/secrets/vault_key
      - source: vault_cert_bundle
        target: /run/secrets/vault_cert
      - source: ca_bundle
        target: /run/secrets/ca
      - source: ca_bundle
        target: /etc/ssl/certs/ca-certificates.crt
      - source: vault_unseal
        target: /run/secrets/vault_unseal
      - source: vault_token
        target: /run/secrets/vault_token
    ports:
      - "8200:8200"
    volumes:
      #- ./vault/data/config.hcl:/vault/config/config.hcl
      - vault:/vault/file

networks:
  web:
    attachable: true
secrets:
  ca:
    name: ${stack_name}_ca
    external: true
  ca_bundle:
    name: ${stack_name}_ca_bundle
    external: true
  ha_cert_bundle:
    name: ${stack_name}_ha_cert_bundle
    external: true
  ha_key:
    name: ${stack_name}_ha_key
    external: true
  home_assistant_mqtt_username:
    name: ${stack_name}_home_assistant_mqtt_username
    external: true
  home_assistant_mqtt_password:
    name: ${stack_name}_home_assistant_mqtt_password
    external: true
  ha_db_cert_bundle:
    name: ${stack_name}_ha_db_cert_bundle
    external: true
  ha_db_key:
    name: ${stack_name}_ha_db_key
    external: true
  mqtt_cert_bundle:
    name: ${stack_name}_mqtt_cert_bundle
    external: true
  mqtt_key:
    name: ${stack_name}_mqtt_key
    external: true
  mqtt_mqtt_username:
    name: ${stack_name}_mqtt_mqtt_username
    external: true
  mqtt_mqtt_password:
    name: ${stack_name}_mqtt_mqtt_password
    external: true
  mqtt_token:
    name: ${stack_name}_mqtt_token
    external: true
  nr_cert_bundle:
    name: ${stack_name}_nr_cert_bundle
    external: true
  nr_key:
    name: ${stack_name}_nr_key
    external: true
  platformio_mqtt_username:
    name: ${stack_name}_platformio_mqtt_username
    external: true
  platformio_mqtt_password:
    name: ${stack_name}_platformio_mqtt_password
    external: true
  platformio_token:
    name: ${stack_name}_platformio_token
    external: true
  portainer_cert_bundle:
    name: ${stack_name}_portainer_cert_bundle
    external: true
  portainer_key:
    name: ${stack_name}_portainer_key
    external: true
  portainer_mqtt_username:
    name: ${stack_name}_portainer_mqtt_username
    external: true
  portainer_mqtt_password:
    name: ${stack_name}_portainer_mqtt_password
    external: true
  portainer_token:
    name: ${stack_name}_portainer_token
    external: true
  node_red_mqtt_username:
    name: ${stack_name}_node_red_mqtt_username
    external: true
  node_red_mqtt_password:
    name: ${stack_name}_node_red_mqtt_password
    external: true
  vault_cert_bundle:
    name: ${stack_name}_vault_cert_bundle
    external: true
  vault_key:
    name: ${stack_name}_vault_key
    external: true
  vault_unseal:
    name: ${stack_name}_vault_unseal
    external: true
  vault_token:
    name: ${stack_name}_vault_token
    external: true
  docs_cert_bundle:
    name: ${stack_name}_docs_cert_bundle
    external: true
  docs_key:
    name: ${stack_name}_docs_key
    external: true
volumes:
  home-assistant-db:
  # TODO: Implement migrations on the actual volume instead. 
  home-assistant-db-migrations:
  mqtt:
  node-red:
  portainer:
  vault:
# Can also use external per http://blog.scottlogic.com/2017/03/01/docker-secrets.html
