version: '3.5'
services:
  vault:
    build:
      context: ./vault
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - SKIP_SETCAP=true
      - VAULT_ADDR=https://vault.local:8200
      # This has been disabled because I don't think they are needed... But not sure enough to remove yet.
      #- CONTAINER_HOSTNAME=vault
      - VAULT_CACERT=/run/secrets/ca
      # This has been disabled because I don't think they are needed... But not sure enough to remove yet.
      #- VAULT_CA=true
    image: althing/vault
    networks:
      web:
        aliases:
          - vault.local
          - vault.scifi.farm
    secrets:
      - source: althing_dev_vault_key
        target: /run/secrets/vault_key
      - source: althing_dev_vault_cert_bundle
        target: /run/secrets/vault_cert
      - source: althing_dev_ca_bundle
        target: /run/secrets/ca
      - source: althing_dev_vault_unseal
        target: /run/secrets/vault_unseal
      - source: althing_dev_vault_token
        target: /run/secrets/vault_token
    ports:
      - "8200:8200"
    volumes:
      - ./vault/data/config.hcl:/vault/config/config.hcl
      - vault:/vault/file
  docs:
    build:
      context: ./docs
    command: jekyll serve
    deploy:
        mode: global
        restart_policy:
          condition: on-failure
    image: althing/docs
    ports:
      - "4000:4000"
    secrets:
      - source: althing_dev_docs_cert_bundle
        target: wiki_cert
      - source: althing_dev_docs_key
        target: wiki_key
      - source: althing_dev_ca
        target: ca
    volumes:
      - ./docs:/srv/jekyll
  ha:
    build:
      context: ./ha
      args:
        - userid=${UID}
        - username=docker
    depends_on:
      - vault
      - mqtt
      - ha_db
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    image: althing/ha
    networks:
      - web
    ports:
      - "8123:8123"
    secrets:
      - source: althing_dev_ha_cert_bundle
        target: ha_cert
        uid: ${UID}
        mode: 0440
      - source: althing_dev_ha_key
        target: ha_key
        uid: ${UID}
        mode: 0400
      - source: althing_dev_ca_bundle
        target: ca
      - source: althing_dev_home_assistant_mqtt_username
        target: mqtt_username
      - source: althing_dev_home_assistant_mqtt_password
        target: mqtt_password
    user: ${UID}
    volumes:
      - ./ha/data/:/config
  ha_db:
    build:
      context: ./ha_db
      args: 
        - userid=${UID}
        - username=postgres
    depends_on:
      - vault
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=homeassistant
      - SSL_CERT_FILE=/run/secrets/ha_db_cert
      - SSL_KEY_FILE=/run/secrets/ha_db_key
      - SSL_CA_FILE=/run/secrets/ca
    image: althing/ha_db
    networks:
      - web
    secrets:
      - source: althing_dev_ha_db_cert_bundle
        target: ha_db_cert
        uid: ${UID}
        mode: 0400
      - source: althing_dev_ha_db_key
        target: ha_db_key
        uid: ${UID}
        mode: 0400
      - source: althing_dev_ca
        target: ca
    user: ${UID}
    volumes:
      - ha_db:/var/lib/postgresql/data
  mqtt:
    build:
      context: ./mqtt
    depends_on:
      - vault
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    image: althing/mqtt
    networks:
      web:
        aliases:
          - mqtt.local
          - mqtt.scifi.farm
    ports:
      - "15672:15672"
      - "8883:8883"
      - "1883:1883"
    secrets:
      - source: althing_dev_mqtt_cert_bundle
        target: mqtt_cert
      - source: althing_dev_mqtt_key
        target: mqtt_key
      - source: althing_dev_ca
        target: ca
    volumes:
        - "./mqtt/config/:/etc/rabbitmq/"
        - mqtt:/var/lib/rabbitmq/
    # Hostname is needed to persist data. 
    hostname: mqtt
  nr:
    build:
      context: ./nr
    depends_on:
      - ha
      - mqtt
      - vault
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    image: althing/node-red
    networks:
      - web
    ports:
      - "1880:1880"
      # Used for debugging. Simply add "--inspect" to the "start" object in /usr/src/node-red/package.json
      # Should be doable via env var: https://nodejs.org/api/cli.html#cli_node_options
      - "9229:9229"
    secrets:
      - source: althing_dev_nr_cert_bundle
        target: nr_cert
        uid: ${UID}
        mode: 0600
      - source: althing_dev_nr_key
        target: nr_key
        uid: ${UID}
        mode: 0600
      - source: althing_dev_node_red_mqtt_username
        target: mqtt_username
      - source: althing_dev_node_red_mqtt_password
        target: mqtt_password
      - source: althing_dev_ca_bundle
        target: ca
        uid: ${UID}
        mode: 0600
      - source: althing_dev_node_red_mqtt_username
        target: mqtt_username
        uid: ${UID}
        mode: 0600
      - source: althing_dev_node_red_mqtt_password
        target: mqtt_password
        uid: ${UID}
        mode: 0600
    user: "0" #${UID}
    volumes:
      - "./nr/data:/data"
      # If you docker cp [container hash]:/usr/src/node-red nr/src/
      # You can work with live running code by uncommenting the following volume>
      #- "./node-red:/usr/src/node-red"
  platformio:
    command: ["sh","-c","docker run --rm --name pio -t --network althing_dev_web -p 3000:3000 -v /home/spencer/src/althing/platformio/entrypoint.py:/workspace/entrypoint.py -e CA=\"$$(cat /run/secrets/ca)\" -e MQTT_USERNAME=\"$$(cat /run/secrets/mqtt_username)\" -e MQTT_PASSWORD=\"$$(cat /run/secrets/mqtt_password)\" -e VAULT_TOKEN=\"$$(cat /run/secrets/token)\" --device /dev/ttyUSB0 althing/platformio"]
    deploy:
        mode: global
        restart_policy:
          condition: on-failure
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    image: docker
    networks:
      - web
    secrets:
      - source: althing_dev_ca_bundle
        target: ca
      - source: althing_dev_platformio_mqtt_username
        target: mqtt_username
      - source: althing_dev_platformio_mqtt_password
        target: mqtt_password
      - source: althing_dev_platformio_token
        target: token
    user: "0" # I suspect I'll be able to remove this. I'd like to do that. 
    volumes:
      - ./platformio/entrypoint.py:/workspace/entrypoint.py
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  web:
    attachable: true
secrets:
  althing_dev_ca:
    external: true
  althing_dev_ca_bundle:
    external: true
  althing_dev_ha_cert_bundle:
    external: true
  althing_dev_ha_key:
    external: true
  althing_dev_home_assistant_mqtt_username:
    external: true
  althing_dev_home_assistant_mqtt_password:
    external: true
  althing_dev_ha_db_cert_bundle:
    external: true
  althing_dev_home_assistant_mqtt_username:
    external: true
  althing_dev_home_assistant_mqtt_password:
    external: true
  althing_dev_ha_db_cert_bundle:
    external: true
  althing_dev_ha_db_key:
    external: true
  althing_dev_mqtt_cert_bundle:
    external: true
  althing_dev_mqtt_key:
    external: true
  althing_dev_nr_cert_bundle:
    external: true
  althing_dev_nr_key:
    external: true
  althing_dev_platformio_mqtt_username:
    external: true
  althing_dev_platformio_mqtt_password:
    external: true
  althing_dev_platformio_token:
    external: true
  althing_dev_node_red_mqtt_username:
    external: true
  althing_dev_node_red_mqtt_password:
    external: true
  althing_dev_vault_cert_bundle:
    external: true
  althing_dev_vault_key:
    external: true
  althing_dev_vault_unseal:
    external: true
  althing_dev_vault_token:
    external: true
  althing_dev_docs_cert_bundle:
    external: true
  althing_dev_docs_key:
    external: true
volumes:
  ha_db:
  mqtt:
  vault:
# Can also use external per http://blog.scottlogic.com/2017/03/01/docker-secrets.html
